- name: Create ansible user and add to sudoers
  hosts: homelab
  become: true
  vars:
    username: ansible
    encrypted_password: "{{ ansible | password_hash('sha512') }}"
    ansible_become_password: Sarita@17
    ansible_become_user: lostinopensrc

  tasks:
    - name: Create user
      user:
        name: "{{ username }}"
        password: "{{ encrypted_password }}"
        createhome: yes
        shell: /bin/bash

    - name: Add user to sudoers
      lineinfile:
        path: /etc/sudoers
        line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
        state: present
        validate: '/usr/sbin/visudo -cf %s'
