- name: Create ansible user and add to sudoers
  hosts: homelab
  become: true
  vars:
    username: ansible
    password: password
    ansible_become_password: ${{secrets.BECOME_PASSWORD}}
    ansible_become_user: ${{ secrets.BECOME_USER  }}

  tasks:
    - name: Create user
      user:
        name: "{{ username }}"
        password: "{{ password }}"
        createhome: yes
        shell: /bin/bash

    - name: Add user to sudoers
      lineinfile:
        path: /etc/sudoers
        line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
        state: present
        validate: '/usr/sbin/visudo -cf %s'
