- name: Create ansible user and add to sudoers
  hosts: homelab
  become: yes
  vars_files:
    - group_vars/all/vars.yaml
    
  tasks:
    - name : Clone Github Repo 
      git:
        repo: 'https://github.com/lostinopensrc/homelab-ansible.git'
        dest: /home/clone
        version: 'feature/create-user'

    - name: Create user
      user:
        state: present
        update_password: always
        name: "{{ item }}"
        password: "{{ lookup('file', '/home/clone/group_vars/all/passwords/' + item) | password_hash('sha512') }}"
        createhome: yes
        shell: /bin/bash
      loop: "{{ users }}"