- name: Create ansible user and add to sudoers
  hosts: homelab
  become: yes
  vars:
    username: myuser1
    encrypted_password: password
  tasks:
    - name: Create user
      user:
        name: "{{ username }}"
        password: "{{ encrypted_password | password_hash('sha512') }}"
        createhome: yes
        shell: /bin/bash