- name: Create ansible user and add to sudoers
  hosts: homelab
  become: yes
  vars:
    users: "{{ groups['all'] }}"

  tasks:
    - name: Create user
      user:
        state: present
        update_password: always
        name: "{{ item }}"
        password: "{{ lookup('file', './group_vars/all/passwords/' + item) | password_hash('sha512') }}"
        createhome: yes
        shell: /bin/bash
      loop: "{{ users }}"