name: Ansible User Creation

on:
  workflow_dispatch:

  pull_request:
    branches:
      - 'main'
    paths:
      - 'group_vars/create/vars.yaml'
      
jobs:
  deploy:
    runs-on: homelab-ansible-runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run User Creation Playbook
      run: |
        ansible-playbook playbooks/user.yaml -i inventory/homelab -vvv