name: Ansible User Creation

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      
jobs:
  deploy:
    runs-on: homelab-ansible-runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run User Creation Playbook
      run: |
        ansible-playbook playbooks/user.yaml -i inventory/homelab